=== mp19084/xmlvalido-grupo02/parte 2/dtd_externa/ejercicio-ii-2b.dtd
<!ELEMENT fichero (ficha+)>
<!ELEMENT ficha (nombre, apellido, direccion, DUI?)>
<!ELEMENT nombre (#PCDATA)>
<!ATTLIST nombre sexo (masculino | femenino) #IMPLIED>
<!ATTLIST nombre edad  CDATA  #IMPLIED>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT DUI (#PCDATA)>
<!ELEMENT publicacion (website+) >
<!ELEMENT website (titulo,a) >
<!ELEMENT titulo (#PCDATA) >
<!ELEMENT a (#PCDATA) >
      <!ATTLIST a  
            href CDATA #IMPLIED
            xmlns CDATA #IMPLIED 
       >

=== mp19084/xmlvalido-grupo02/parte 2/dtd_externa/ejercicio-ii-1b-dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="estilo.css" ?>
<!DOCTYPE fichero SYSTEM "ejercicio-ii-2b.dtd">
<!-- ejemplodtd1.xml G04 -->
<fichero>
 <ficha>
  <nombre edad="17">Angelina</nombre>
  <apellido>Fernandez</apellido>
  <direccion>c/Ulises, 36</direccion>
  <publicacion>
  <website>
  <titulo>Para volver al index, presiona:</titulo>
  <a xmlns="http://www.w3.org/1999/xhtml" href="../../index.html">INDICE</a>
  </website>
  </publicacion>
 </ficha>
</fichero>
