=== mp19084/xmlvalido-grupo02/parte 4/tareas.dtd
<!â€”fichero4-4.dtd -->
<!ELEMENT equipo (fichaJugador+)>
<!ELEMENT fichaJugador (nombre, apellido, posicion, nacionalidad?)>
<!ELEMENT nombre (#PCDATA)>
<!ATTLIST nombre sexo (masculino|femenino) #REQUIRED>
<!ATTLIST nombre edad  CDATA  #IMPLIED>
<!ATTLIST nombre estatura  CDATA  #IMPLIED>
<!ATTLIST nombre peso  CDATA  #REQUIRED>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT posicion (#PCDATA)>
<!ELEMENT nacionalidad (#PCDATA)>
<!ELEMENT publicacion (website+) >
<!ELEMENT website (titulo,a) >
<!ELEMENT titulo (#PCDATA) >
<!ELEMENT a (#PCDATA) >
<!ATTLIST a  
href CDATA #IMPLIED
xmlns CDATA #IMPLIED 
>

=== mp19084/xmlvalido-grupo02/parte 4/tareas.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="tareas.css" ?>
<!DOCTYPE fichero SYSTEM "tareas.dtd">
<equipo>
 <fichaJugador>
  <nombre sexo="masculino" edad="22" estatura="194" pero="85">
         virgil 
  </nombre>
  <apellido>van dijk</apellido>
  <posicion>defensa</posicion>
  <nacionalidad>neerlandés</nacionalidad>
</fichaJugador>
 <fichaJugador>
  <nombre sexo="masculino" edad="38" estatura="174" pero="80">
         Leonel Andres 
  </nombre>
  <apellido>Messi</apellido>
  <posicion>delantero</posicion>
  <nacionalidad>argentino</nacionalidad>
</fichaJugador>
<publicacion>
 <website>
<titulo>Para volver al index, presiona:</titulo>
<a xmlns="http://www.w3.org/1999/xhtml" href="../index.html">INDICE</a>
</website>
</publicacion>
</equipo>
